/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VirtualRouteImport } from './routes/virtual'
import { Route as SmcRouteImport } from './routes/smc'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as QuantRouteImport } from './routes/quant'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PairsRouteImport } from './routes/pairs'
import { Route as MomentumRouteImport } from './routes/momentum'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualRoute = VirtualRouteImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const SmcRoute = SmcRouteImport.update({
  id: '/smc',
  path: '/smc',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantRoute = QuantRouteImport.update({
  id: '/quant',
  path: '/quant',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PairsRoute = PairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentumRoute = MomentumRouteImport.update({
  id: '/momentum',
  path: '/momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/calculator': typeof CalculatorRoute
  '/momentum': typeof MomentumRoute
  '/pairs': typeof PairsRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/quant': typeof QuantRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/calculator': typeof CalculatorRoute
  '/momentum': typeof MomentumRoute
  '/pairs': typeof PairsRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/quant': typeof QuantRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/calculator': typeof CalculatorRoute
  '/momentum': typeof MomentumRoute
  '/pairs': typeof PairsRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/quant': typeof QuantRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/smc': typeof SmcRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/calculator'
    | '/momentum'
    | '/pairs'
    | '/paper'
    | '/performance'
    | '/quant'
    | '/scan'
    | '/settings'
    | '/smc'
    | '/virtual'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/calculator'
    | '/momentum'
    | '/pairs'
    | '/paper'
    | '/performance'
    | '/quant'
    | '/scan'
    | '/settings'
    | '/smc'
    | '/virtual'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/calculator'
    | '/momentum'
    | '/pairs'
    | '/paper'
    | '/performance'
    | '/quant'
    | '/scan'
    | '/settings'
    | '/smc'
    | '/virtual'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  CalculatorRoute: typeof CalculatorRoute
  MomentumRoute: typeof MomentumRoute
  PairsRoute: typeof PairsRoute
  PaperRoute: typeof PaperRoute
  PerformanceRoute: typeof PerformanceRoute
  QuantRoute: typeof QuantRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SmcRoute: typeof SmcRoute
  VirtualRoute: typeof VirtualRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual': {
      id: '/virtual'
      path: '/virtual'
      fullPath: '/virtual'
      preLoaderRoute: typeof VirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smc': {
      id: '/smc'
      path: '/smc'
      fullPath: '/smc'
      preLoaderRoute: typeof SmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quant': {
      id: '/quant'
      path: '/quant'
      fullPath: '/quant'
      preLoaderRoute: typeof QuantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairs': {
      id: '/pairs'
      path: '/pairs'
      fullPath: '/pairs'
      preLoaderRoute: typeof PairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/momentum': {
      id: '/momentum'
      path: '/momentum'
      fullPath: '/momentum'
      preLoaderRoute: typeof MomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  CalculatorRoute: CalculatorRoute,
  MomentumRoute: MomentumRoute,
  PairsRoute: PairsRoute,
  PaperRoute: PaperRoute,
  PerformanceRoute: PerformanceRoute,
  QuantRoute: QuantRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SmcRoute: SmcRoute,
  VirtualRoute: VirtualRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
